Add f5-rest-node-lib sample workers
f5devcentral/f5-rest-examples pull request #8
Opened 2018-03-29 22:52 UTC by dajiabao

2018-03-29 23:08 UTC, elv1s requested changes

2018-03-29 23:08 UTC, elv1s commented on workers/collections/authorWorker.js
> +        this.WORKER_URI_PATH = "shared/authors"; //demo purpose, final collection URI convention may change
please remove the comment from this line, and the next

2018-03-29 23:08 UTC, elv1s commented on workers/collections/authorWorker.js
> +            netWorth: this.netWorthDefaultUpdate(item)
minor - please move this function off of the prorotype and into a private function

2018-03-29 23:08 UTC, elv1s commented on workers/fileWorker.js
> +module.exports = FileWorker;
minor - newline at end of file

2018-03-29 23:08 UTC, elv1s commented on workers/greeting/greetingWorker.js
> +module.exports = GreetingWorker;
minor - newline at end of file

2018-03-29 23:08 UTC, elv1s commented on workers/persistedWorker.js
> +/*
can you remove this persistedWorker from the pull request. We want to encourage the collection/singleton worker pattern for stateful workers. Thanks!

2018-03-29 23:08 UTC, elv1s commented on workers/singletons/meWorker.js
> +                'alonso@f5.com'
can you change the name please?

2018-03-29 23:08 UTC, elv1s commented on workers/singletons/meWorker.js
> +        return require('odata/sample/models/person');
inline the schema please

2018-03-29 23:08 UTC, elv1s commented on workers/singletons/youWorker.js
> +                FirstName: 'Keith',
change name

2018-03-29 23:08 UTC, elv1s commented on workers/singletons/youWorker.js
> +        return require('odata/sample/models/person');
inline schema

2018-03-29 23:47 UTC, dajiabao commented on workers/fileWorker.js
> +module.exports = FileWorker;
newline added

2018-03-29 23:47 UTC, dajiabao commented on workers/greeting/greetingWorker.js
> +module.exports = GreetingWorker;
newline added

2018-03-30 02:37 UTC, elv1s approved these changes
ship it!

2018-03-30 16:30 UTC, merged